name: Docker CI

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        run: |
          docker build -t $DOCKER_USERNAME/go-blog:latest .
          docker push $DOCKER_USERNAME/go-blog:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 (Debug File Transfer)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          host_key_checking: false # Temporarily disabled - address for production
          # Copy docker-compose.yml to the server using the action's file transfer
          source: "golang-simple-blog-app/docker-compose.yml"
          target: "/home/${{ secrets.EC2_USERNAME }}/golang-simple-blog-app/docker-compose.yml"
          script: |
            # Define target directory
            TARGET_DIR="/home/${{ secrets.EC2_USERNAME }}/golang-simple-blog-app"

            # Create target directory if it doesn't exist
            mkdir -p $TARGET_DIR
            echo "Target directory $TARGET_DIR created or already exists."

            # List contents of the target directory to check for the file
            echo "Listing contents of $TARGET_DIR:"
            ls -la $TARGET_DIR

            # Exit the script after listing, we are just debugging file transfer
            exit 0 